modules:
  - module_type: llama_index_chunk
    chunk_method: Token
    chunk_size: [512]
    chunk_overlap: 24
  - module_type: llama_index_chunk
    chunk_method: [SentenceWindow]
    sentence_splitter: kiwi